### ISSUE TITLE
Not detecting Discord M1 Mac

### ISSUE THREAD

**Issue by hotsno** [qwertyquerty/pypresence#156]
I get the following error on a M1 Mac:
`pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.`

After some time, pypresence stops detecting the Discord install and crashes with the above error. After running the script again, it still doesn't detect it, but restarting Discord always fixes this error.

**Comment by Hunter2807** [comment]
@hotsno sorry for a late response, but it is more of a Discord Issue since this lib depends on a socket-like file which Discord creates in your laptop/computer, to communicate with the Discord API and display the presence.

**Comment by LewdNeko** [comment]
> @hotsno sorry for a late response, but it is more of a Discord Issue since this lib depends on a socket-like file which Discord creates in your laptop/computer, to communicate with the Discord API and display the presence.

I don't think the issue is that it can't be found all, the issue is that it can't be found after some time.

Could you try replicating [utils.get_ipc_path()](https://github.com/qwertyquerty/pypresence/blob/4fc19b14284d87e2e02ea57c74722ee9a4ff20e3/pypresence/utils.py#L26) with some debugging and calling it until it stops detecting again?

**Comment by wxllow** [comment]
I'm having the same issue and utils.get_ipc_path() returns `'/var/folders/z3/k75_3rc506q6kc5v7hlnx7rc0000gn/T/discord-ipc-1'`, which doesn't exist

**Comment by JoshPaulie** [comment]
My M1 is also not detecting discord. 😣 Hoping to use this soon
