### ISSUE TITLE
Error with displaying current time in the Start Timestamp

### ISSUE THREAD

**Issue by Suntrax** [qwertyquerty/pypresence#176]
So I know that Discord uses **_Epoch Unix Time_** to display the timestamp. And I'm using (as shown in the screenshot below) the Python comand from the 'time' package/library called **_time.time()_**, which returns the current Epoch Unix Time. But for some reason Discord always starts counting up from 00:00 when I run this code instead of displaying the current time.

![Screenshot 2022-08-08 000110](https://user-images.githubusercontent.com/89277156/183312653-b8feb24b-8296-45c9-9d12-1f69a6d9796b.png)

**Comment by dannynotsmart** [comment]
That’s because the `start` keyword is used for the elapsed time. It doesn’t display any time at all, but rather the time passed since the given Epoch time.

If you want to display your current time on your rich presence (ex: `It is {4:17PM} for me`), you’d have to update that in one of the text fields instead.
